import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/app_provider.dart';
import 'contact_detail_screen.dart';

class ContactsScreen extends ConsumerStatefulWidget { const ContactsScreen({super.key}); @override ConsumerState<ContactsScreen> createState() => _ContactsScreenState(); }
class _ContactsScreenState extends ConsumerState<ContactsScreen> { final search = TextEditingController(); String filter = 'customer'; @override Widget build(BuildContext context) { final d = ref.watch(appProvider); final q = search.text.toLowerCase(); final list = d.contacts.where((c) => c.type == filter && (c.name.toLowerCase().contains(q) || c.phone.contains(q))).toList(); return Scaffold(appBar: AppBar(title: const Text('Khata')), floatingActionButton: FloatingActionButton.extended(onPressed: () => _add(), icon: const Icon(Icons.add), label: const Text('Add')), body: Column(children: [Padding(padding: const EdgeInsets.fromLTRB(16, 12, 16, 4), child: TextField(controller: search, onChanged: (_) => setState(() {}), decoration: const InputDecoration(prefixIcon: Icon(Icons.search), hintText: 'Search customers or suppliers'))), Padding(padding: const EdgeInsets.all(8), child: SegmentedButton<String>(segments: const [ButtonSegment(value: 'customer', label: Text('Customers')), ButtonSegment(value: 'supplier', label: Text('Suppliers'))], selected: {filter}, onSelectionChanged: (s) => setState(() => filter = s.first))), Expanded(child: list.isEmpty ? const Center(child: Text('No contacts yet')) : ListView.builder(itemCount: list.length, itemBuilder: (_, i) { final c = list[i]; final balance = filter == 'customer' ? d.receivableFor(c.id) : d.payableFor(c.id); return ListTile(onTap: () => Navigator.push(context, MaterialPageRoute(builder: (_) => ContactDetailScreen(contactId: c.id))), leading: CircleAvatar(child: Text(c.name.isEmpty ? '?' : c.name[0].toUpperCase())), title: Text(c.name), subtitle: Text(c.phone.isEmpty ? 'No phone' : c.phone), trailing: Text('PKR ${balance.toStringAsFixed(0)}', style: TextStyle(fontWeight: FontWeight.bold, color: balance > 0 ? Theme.of(context).colorScheme.primary : null))); }))])); }
Future<void> _add() async { final name = TextEditingController(); final phone = TextEditingController(); await showDialog(context: context, builder: (_) => AlertDialog(title: Text('Add ${filter}'), content: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: name, decoration: const InputDecoration(labelText: 'Name')), const SizedBox(height: 10), TextField(controller: phone, keyboardType: TextInputType.phone, decoration: const InputDecoration(labelText: 'Phone'))]), actions: [TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')), FilledButton(onPressed: () { if (name.text.trim().isNotEmpty) { ref.read(appProvider.notifier).addContact(name.text, phone.text, filter); Navigator.pop(context); } }, child: const Text('Save'))])); }
}
